/**
 * Generates fpl/data/demo-snapshot.json - a fictional league used to exercise
 * the app before real data is loaded. Clubs and players are invented on
 * purpose so demo data can never be mistaken for the real thing.
 *
 *   node tools/make_demo_snapshot.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';

const TEAMS = 20;
const GAMEWEEKS = 38;
const rng = mulberry32(20262027);

const teams = Array.from({ length: TEAMS }, (_, i) => {
  const tier = i < 5 ? 0 : i < 12 ? 1 : 2;          // strong, mid, weak
  return {
    id: i + 1,
    name: `Demo Club ${String.fromCharCode(65 + i)}`,
    short_name: `D${String.fromCharCode(65 + i)}`,
    strength: 5 - tier,
    strength_attack_home: 1250 - tier * 120,
    strength_attack_away: 1200 - tier * 120,
    strength_defence_home: 1250 - tier * 120,
    strength_defence_away: 1200 - tier * 120,
    tier,
  };
});

const POSITION_PLAN = [
  { type: 1, count: 2, price: [40, 60] },
  { type: 2, count: 7, price: [40, 70] },
  { type: 3, count: 8, price: [45, 130] },
  { type: 4, count: 4, price: [45, 120] },
];

const FIRST = ['Alex', 'Ben', 'Caleb', 'Diego', 'Elias', 'Finn', 'Gabriel', 'Hugo', 'Ivan', 'Jonas',
  'Kai', 'Luca', 'Mateo', 'Noah', 'Omar', 'Pablo', 'Rafa', 'Samir', 'Tomas', 'Viktor'];
const LAST = ['Alvarez', 'Bergman', 'Costa', 'Dumont', 'Eriksen', 'Ferreira', 'Grimaldo', 'Halvorsen',
  'Ibrahim', 'Jansen', 'Koval', 'Lindqvist', 'Moretti', 'Novak', 'Oyelaran', 'Petrov', 'Quintero',
  'Rossi', 'Silva', 'Tanaka'];

const elements = [];
let id = 1;
for (const team of teams) {
  for (const plan of POSITION_PLAN) {
    for (let i = 0; i < plan.count; i++) {
      const nailed = i === 0 || (plan.type !== 1 && i < plan.count / 2);
      const quality = clamp(1 - team.tier * 0.18 - i * 0.12 + (rng() - 0.5) * 0.2, 0.15, 1);
      const minutes = Math.round((nailed ? 78 : 28) * quality * 3 + rng() * 90) * 1;
      const price = Math.round(plan.price[0] + (plan.price[1] - plan.price[0]) * quality ** 2 / 5) * 1;

      elements.push({
        id,
        web_name: `${LAST[(id * 7) % LAST.length]}`,
        first_name: FIRST[(id * 3) % FIRST.length],
        second_name: LAST[(id * 7) % LAST.length],
        element_type: plan.type,
        team: team.id,
        now_cost: Math.max(38, Math.min(145, price)),
        status: rng() < 0.05 ? (rng() < 0.5 ? 'i' : 'd') : 'a',
        chance_of_playing_next_round: null,
        news: '',
        minutes,
        starts: Math.round(minutes / 85),
        form: round1(quality * 6 * (0.6 + rng() * 0.8)),
        points_per_game: round1(quality * 5.5),
        total_points: Math.round(quality * 60),
        ep_next: round1(quality * 5.2),
        goals_scored: plan.type >= 3 ? Math.round(quality * 6 * rng()) : Math.round(quality * rng()),
        assists: Math.round(quality * 4 * rng()),
        clean_sheets: Math.round(quality * 3 * rng()),
        goals_conceded: Math.round((1 + team.tier) * 3 * rng()),
        saves: plan.type === 1 ? Math.round(minutes / 90 * 3) : 0,
        bonus: Math.round(quality * 8 * rng()),
        bps: Math.round(quality * 200),
        yellow_cards: Math.round(rng() * 3),
        red_cards: 0,
        own_goals: 0,
        penalties_saved: 0,
        penalties_missed: 0,
        expected_goals_per_90: round2(plan.type === 4 ? quality * 0.62 : plan.type === 3 ? quality * 0.34 : quality * 0.06),
        expected_assists_per_90: round2(plan.type === 3 ? quality * 0.30 : quality * 0.15),
        defensive_contribution_per_90: plan.type === 1 ? null
          : round1(plan.type === 2 ? 6 + rng() * 7 : 3 + rng() * 8),
        selected_by_percent: round1(quality * 30).toFixed(1),
      });
      id++;
    }
  }
}

// Round-robin-ish schedule: each gameweek pairs teams by a rotating offset.
const fixtures = [];
let fixtureId = 1;
for (let gw = 1; gw <= GAMEWEEKS; gw++) {
  const rotated = rotate(teams.map((t) => t.id), gw);
  for (let i = 0; i < TEAMS / 2; i++) {
    const home = gw % 2 === 0 ? rotated[i] : rotated[TEAMS - 1 - i];
    const away = gw % 2 === 0 ? rotated[TEAMS - 1 - i] : rotated[i];
    fixtures.push({
      id: fixtureId++,
      event: gw,
      team_h: home,
      team_a: away,
      team_h_difficulty: difficulty(away, true),
      team_a_difficulty: difficulty(home, false),
      finished: false,
      kickoff_time: null,
    });
  }
}

const events = Array.from({ length: GAMEWEEKS }, (_, i) => ({
  id: i + 1,
  name: `Gameweek ${i + 1}`,
  deadline_time: new Date(Date.UTC(2026, 7, 21 + i * 7, 17, 30)).toISOString(),
  is_current: false,
  is_next: i === 0,
  finished: false,
}));

mkdirSync('fpl/data', { recursive: true });
writeFileSync('fpl/data/demo-snapshot.json', JSON.stringify({
  demo: true,
  generated_at: new Date().toISOString(),
  source: 'generated by tools/make_demo_snapshot.mjs - fictional data',
  elements, teams: teams.map(({ tier, ...t }) => t), events, fixtures,
}, null, 0));

console.log(`Wrote fpl/data/demo-snapshot.json: ${elements.length} players, ${fixtures.length} fixtures`);

function difficulty(opponentId, atHome) {
  const tier = teams[opponentId - 1].tier;
  const base = tier === 0 ? 5 : tier === 1 ? 3 : 2;
  return Math.max(1, Math.min(5, base + (atHome ? 0 : 1) - (atHome ? 1 : 0)));
}
function rotate(arr, n) { const k = n % arr.length; return [...arr.slice(k), ...arr.slice(0, k)]; }
function mulberry32(a) {
  return function () {
    a |= 0; a = a + 0x6D2B79F5 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function clamp(v, lo, hi) { return Math.min(hi, Math.max(lo, v)); }
function round1(v) { return Math.round(v * 10) / 10; }
function round2(v) { return Math.round(v * 100) / 100; }
